name: PVS-Studio C# Analysis

on: workflow_dispatch

jobs:
  analyze:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and install PVS-Studio
        run: |
          Invoke-WebRequest -Uri "https://files.viva64.com/pvs-studio.exe" -OutFile "pvs-studio.exe"
          Start-Process .\pvs-studio.exe -ArgumentList "/SILENT" -Wait

      - name: Activate license
        run: |
          $license = "${{ secrets.PVS_STUDIO_CREDENTIALS }}"
          & "C:\Program Files (x86)\PVS-Studio\PVS-Studio_Cmd.exe" -i $license

      - name: Run PVS-Studio for C#
        run: |
          & "C:\Program Files (x86)\PVS-Studio\PVS-Studio_Cmd.exe" -t cs -o PVS-Studio.log SharpNav.sln

      - name: Convert to SARIF
        run: |
          & "C:\Program Files (x86)\PVS-Studio\plog-converter.exe" -t sarif -o pvs-report.sarif PVS-Studio.log

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: pvs-report.sarif
