name: PVS-Studio C# Analysis

on: workflow_dispatch

jobs:
  analyze:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PVS-Studio
        run: |
          choco install pvs-studio

      - name: Activate license
        run: |
          & "C:\Program Files (x86)\PVS-Studio\PVS-Studio_Cmd.exe" Credentials ${{ secrets.PVS_STUDIO_CREDENTIALS }}

      - name: Run PVS-Studio for C#
        run: |
          & "C:\Program Files (x86)\PVS-Studio\PVS-Studio_Cmd.exe" -t cs -o PVS-Studio.log SharpNav.sln

      - name: Convert to SARIF
        run: |
          & "C:\Program Files (x86)\PVS-Studio\plog-converter.exe" -t sarif -o pvs-report.sarif PVS-Studio.log

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: pvs-report.sarif
